import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SiderBar from '@/layouts/siderbar/siderbar'

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Scheduled',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (  
    <html lang="en">
      <body className={inter.className}>
        <div className="siderbar">
          <SiderBar/>
        </div>
        <div className="container">{children}</div>
      </body>
    </html>
  )
}
